//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELEMENTO_CARRITO
    {
        public int idElemento { get; set; }
        public int cantidad { get; set; }
        public decimal precioDelElemento { get; set; }
        public int idCarrito { get; set; }
        public int idProducto { get; set; }
    
        public virtual CARRITO CARRITO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
